### ISSUE TITLE
Is windows supported?

### ISSUE THREAD

**Issue by Wizek** [dmbarbour/haskell-lmdb#3]
And if so, could someone write a few lines on how to build on windows?

I got as far as `slack`/`cabal` telling me:

```
Missing dependency on a foreign library:
* Missing C library: lmdb
This problem can usually be solved by installing the system package that
provides this library (you may need the "-dev" version). If the library is
already installed but in a non-standard location then you can use the flags
--extra-include-dirs= and --extra-lib-dirs= to specify where it is.
```

I built the C liblmdb library by running `make` with a MSYS2 MinGW 64bit terminal: https://gist.github.com/Wizek/7f139b58aa4483f0f89457b7e2382e2a

And with cabal I was able to go further specifying the `--extra-{include,lib}-dirs=` for `cabal configure`:
https://gist.github.com/Wizek/d0d9f17806799cb7a66420a7f550ed80

And then I ran into the above linker errors.

Is there anything that I am missing, or am I making a mistake? How could I proceed?

p.s. On linux getting dependencies was as simple as `sudo apt install liblmdb-dev` and then building succeeded.

**Comment by TerrorJack** [comment]
@Wizek I'm using `stack` to build, and simply executing `stack exec pacman -- -S mingw-w64-x86_64-lmdb` shall install the library. `stack build lmdb` works out of the box. There's no need to run `make` manually.

**Comment by Wizek** [comment]
@TerrorJack That's terrific news! Not sure how I missed the mingw package. Although it seems I'm not quite yet out of the woods:

https://gist.github.com/Wizek/b296b2f47ae03e1527087c665a07c930

`pacman` seems to install the package just fine and then `stack build` does not find the C library lmdb.
And indeed, `pkg-config lmdb --modversion`  doesn't find a `lmdb.pc` file either.

```
Package lmdb was not found in the pkg-config search path.
Perhaps you should add the directory containing `lmdb.pc'
to the PKG_CONFIG_PATH environment variable
No package 'lmdb' found
```

Which is corroborated by `pacman -Ql mingw-w64-x86_64-lmdb` not listing any `.pc` file as part of the package either.

```
$ pacman -Ql mingw-w64-x86_64-lmdb
mingw-w64-x86_64-lmdb /mingw64/
mingw-w64-x86_64-lmdb /mingw64/bin/
mingw-w64-x86_64-lmdb /mingw64/bin/liblmdb.dll
mingw-w64-x86_64-lmdb /mingw64/bin/mdb_copy.exe
mingw-w64-x86_64-lmdb /mingw64/bin/mdb_dump.exe
mingw-w64-x86_64-lmdb /mingw64/bin/mdb_load.exe
mingw-w64-x86_64-lmdb /mingw64/bin/mdb_stat.exe
mingw-w64-x86_64-lmdb /mingw64/include/
mingw-w64-x86_64-lmdb /mingw64/include/lmdb.h
mingw-w64-x86_64-lmdb /mingw64/lib/
mingw-w64-x86_64-lmdb /mingw64/lib/liblmdb.a
mingw-w64-x86_64-lmdb /mingw64/lib/liblmdb.dll.a
mingw-w64-x86_64-lmdb /mingw64/share/
mingw-w64-x86_64-lmdb /mingw64/share/man/
mingw-w64-x86_64-lmdb /mingw64/share/man/man1/
mingw-w64-x86_64-lmdb /mingw64/share/man/man1/mdb_copy.1.gz
mingw-w64-x86_64-lmdb /mingw64/share/man/man1/mdb_dump.1.gz
mingw-w64-x86_64-lmdb /mingw64/share/man/man1/mdb_load.1.gz
mingw-w64-x86_64-lmdb /mingw64/share/man/man1/mdb_stat.1.gz
```

Any ideas how to continue from here?
Also, @TerrorJack what does your `pkg-config lmdb --modversion` or `stack exec pkg-config -- lmdb --modversion` output?

**Comment by TerrorJack** [comment]
@Wizek Try add the following lines to your `stack.yaml` (or global `config.yaml`):

```yaml
extra-lib-dirs:
- C:\msys64\mingw64\lib
- C:\msys64\mingw64\bin
extra-include-dirs:
- C:\msys64\mingw64\include
```

(Change the msys2 path to point to your stack managed installation)

This package links with lmdb but not via pkg-config.

**Comment by Wizek** [comment]
It seems to be building now! Thanks a lot @TerrorJack!

**Comment by Wizek** [comment]
And victory! I was able to build my app fully. Thanks again @TerrorJack!
